server:
  port: 8080

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/TESTDB
    username: TESTUSER
    password: PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 614504679861-k787kpnc6ts6408pabh583dfjbg3khr0.apps.googleusercontent.com
            client-secret: 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

# Spring Data JPA
spring.jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
# これがないとテーブル名が小文字になってしまい、RDSでエラーになる
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    root: INFO
