server:
  port: 8080

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/TESTDB
    username: TESTUSER
    password: PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver

# Spring Data JPA
spring.jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
# これがないとテーブル名が小文字になってしまい、RDSでエラーになる
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    root: INFO
