name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2

    - name: Log in to GitHub Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew build -p ./spring_cicd_person -x test

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./spring_cicd_person/Dockerfile
        push: true
        tags: ghcr.io/kenyasaitoh/spring_cicd_person:latest
