-- 配送テーブル
CREATE TABLE SHIPPING (
ID              INT AUTO_INCREMENT PRIMARY KEY,
ORDER_DATE_TIME TIMESTAMP,
CLIENT_NAME     VARCHAR(255),
RECEIVE_DATE    DATE,
BAGGAGE_COUNT   INT,
TOTAL_PRICE     INT
);