CREATE TABLE PUBLISHER (
PUBLISHER_ID   INT PRIMARY KEY,     -- 出版社番号
PUBLISHER_NAME VARCHAR(30) NOT NULL -- 出版社名
);

CREATE TABLE CATEGORY (
CATEGORY_ID   INT PRIMARY KEY,     -- カテゴリ番号
CATEGORY_NAME VARCHAR(20) NOT NULL -- カテゴリ名
);

CREATE TABLE BOOK (
BOOK_ID      INT PRIMARY KEY,      -- 書籍番号
BOOK_NAME    VARCHAR(80) NOT NULL, -- 書籍名
AUTHOR       VARCHAR(40) NOT NULL, -- 著者
CATEGORY_ID  INT NOT NULL,         -- カテゴリ番号
PUBLISHER_ID INT NOT NULL,         -- 出版社番号
PRICE        INT NOT NULL,         -- 価格
CONSTRAINT FK_PUBLISHER_ID FOREIGN KEY(PUBLISHER_ID)
    REFERENCES PUBLISHER(PUBLISHER_ID)
);

CREATE TABLE CUSTOMER (
CUSTOMER_ID   INT PRIMARY KEY,      -- 顧客番号
CUSTOMER_NAME VARCHAR(30) NOT NULL, -- 顧客名
PASSWORD      VARCHAR(20) NOT NULL, -- パスワード
EMAIL         VARCHAR(30) NOT NULL, -- 電子メール
BIRTHDAY      DATE,                 -- 生年月日
ADDRESS       VARCHAR(40),          -- 住所
CONSTRAINT EMAIL_UNIQUE UNIQUE(EMAIL)
);

CREATE TABLE ORDER_CONTENT (
ORDER_ID         INT PRIMARY KEY,      -- 注文番号
ORDER_DATE       DATE NOT NULL,        -- 注文日
CUSTOMER_ID      INT NOT NULL,         -- 顧客番号
TOTAL_PRICE      INT NOT NULL,         -- 注文金額合計
DELIVERY_PRICE   INT NOT NULL,         -- 配送料金
DELIVERY_ADDRESS VARCHAR(30) NOT NULL, -- 配送先住所
SETTLEMENT_TYPE  INT NOT NULL,         -- 決済方法
CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY(CUSTOMER_ID)
    REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE ORDER_LINE (
ORDER_ID      INT,          -- 注文番号
ORDER_LINE_ID INT,          -- 注文明細番号
BOOK_ID       INT NOT NULL, -- 書籍番号
COUNT         INT NOT NULL, -- 注文数
CONSTRAINT PK_ORDER_LINE
    PRIMARY KEY(ORDER_ID, ORDER_LINE_ID),
CONSTRAINT FK_ORDER_ID FOREIGN KEY(ORDER_ID)
    REFERENCES ORDER_CONTENT(ORDER_ID)
    ON DELETE CASCADE,
CONSTRAINT FK_BOOK_ID FOREIGN KEY(BOOK_ID)
    REFERENCES BOOK(BOOK_ID)
);