server:
  port: 8080

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html

logging:
  level:
    root: INFO
    org.springframework: ERROR
    pro.kensait.spring.mvc.calc: INFO
#  file: spring_mvc_calc_3.log