name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2

    - name: Log in to GitHub Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
 
    - name: Build with Gradle
      run: |
        chmod +x ./spring_projects/spring_mvc_calc/gradlew
        ./spring_projects/spring_mvc_calc/gradlew build -p ./spring_mvc_person -x test

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./spring_projects/spring_mvc_person/Dockerfile
        push: true
        tags: ghcr.io/kenyasaitoh/spring_mvc_person:latest
